name: wedevs_task
version: 1.0.0+1
publish_to: 'none'
description: "WeDevs Task"
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  logger: ^2.3.0
  nb_utils: ^7.0.2
  path: any
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path_ios: "assets/images/launcher_icon.png"
  image_path_android: "assets/images/launcher_icon.png"
  ios: true
  android: true
  adaptive_icon_background: "#ffffff"
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/


